exports.TODOS = [
  {
    userId: 1,
    id: 1,
    title: "Complete the project proposal",
    completed: false,
  },
  {
    userId: 2,
    id: 2,
    title: "Respond to client emails",
    completed: false,
  },
  {
    userId: 3,
    id: 3,
    title: "Finish the quarterly report",
    completed: false,
  },
  {
    userId: 4,
    id: 4,
    title: "Schedule meeting with marketing team",
    completed: true,
  },
  {
    userId: 5,
    id: 5,
    title: "Prepare the presentation slides for tomorrow's meeting",
    completed: false,
  },
  {
    userId: 6,
    id: 6,
    title: "Update website content",
    completed: false,
  },
  {
    userId: 7,
    id: 7,
    title: "Review and approve budget for next quarter",
    completed: false,
  },
  {
    userId: 8,
    id: 8,
    title: "Organize team-building event",
    completed: true,
  },
  {
    userId: 9,
    id: 9,
    title: "Research new software tools for project management",
    completed: false,
  },
  {
    userId: 10,
    id: 10,
    title: "Conduct performance reviews for team members",
    completed: true,
  },
  {
    userId: 11,
    id: 11,
    title: "Finalize contract with new vendor",
    completed: true,
  },
  {
    userId: 12,
    id: 12,
    title: "Prepare financial forecast for next year",
    completed: true,
  },
  {
    userId: 13,
    id: 13,
    title: "Clean up project management tools and software",
    completed: false,
  },
  {
    userId: 14,
    id: 14,
    title: "Organize team training session on new tools",
    completed: true,
  },
  {
    userId: 15,
    id: 15,
    title: "Submit tax documentation to accountant",
    completed: true,
  },
  {
    userId: 16,
    id: 16,
    title: "Create a social media content calendar",
    completed: true,
  },
  {
    userId: 17,
    id: 17,
    title: "Analyze customer feedback for product improvements",
    completed: true,
  },
  {
    userId: 18,
    id: 18,
    title: "Research competitors' pricing strategies",
    completed: false,
  },
  {
    userId: 19,
    id: 19,
    title: "Plan team holiday schedule",
    completed: true,
  },
  {
    userId: 20,
    id: 20,
    title: "Develop a marketing strategy for new product launch",
    completed: true,
  },
  {
    userId: 21,
    id: 21,
    title: "Prepare business proposal for potential partner",
    completed: false,
  },
  {
    userId: 22,
    id: 22,
    title: "Update product catalog for next season",
    completed: false,
  },
  {
    userId: 23,
    id: 23,
    title: "Hold interview for new team members",
    completed: true,
  },
  {
    userId: 24,
    id: 24,
    title: "Create customer loyalty program",
    completed: false,
  },
  {
    userId: 25,
    id: 25,
    title: "Test website for bugs and performance issues",
    completed: true,
  },
  {
    userId: 26,
    id: 26,
    title: "Arrange a feedback session with customers",
    completed: false,
  },
  {
    userId: 27,
    id: 27,
    title: "Write content for new blog post",
    completed: true,
  },
  {
    userId: 28,
    id: 28,
    title: "Schedule training session for sales team",
    completed: true,
  },
  {
    userId: 29,
    id: 29,
    title: "Audit company expenses for last quarter",
    completed: false,
  },
  {
    userId: 30,
    id: 30,
    title: "Plan team retreat for next month",
    completed: true,
  },
  {
    userId: 31,
    id: 31,
    title: "Follow up with suppliers for overdue orders",
    completed: false,
  },
  {
    userId: 32,
    id: 32,
    title: "Set up CRM for customer relationship management",
    completed: true,
  },
  {
    userId: 33,
    id: 33,
    title: "Coordinate with design team for marketing materials",
    completed: false,
  },
  {
    userId: 34,
    id: 34,
    title: "Check and reorder inventory for upcoming sales",
    completed: false,
  },
  {
    userId: 35,
    id: 35,
    title: "Design new website layout",
    completed: true,
  },
  
];
