exports.TODOS = [
  {
    userId: 1,
    id: 1,
    title: "Complete the project proposal",
    completed: false,
  },
  {
    userId: 1,
    id: 2,
    title: "Respond to client emails",
    completed: false,
  },
  {
    userId: 1,
    id: 3,
    title: "Finish the quarterly report",
    completed: false,
  },
  {
    userId: 1,
    id: 4,
    title: "Schedule meeting with marketing team",
    completed: true,
  },
  {
    userId: 1,
    id: 5,
    title: "Prepare the presentation slides for tomorrow's meeting",
    completed: false,
  },
  {
    userId: 1,
    id: 6,
    title: "Update website content",
    completed: false,
  },
  {
    userId: 1,
    id: 7,
    title: "Review and approve budget for next quarter",
    completed: false,
  },
  {
    userId: 1,
    id: 8,
    title: "Organize team-building event",
    completed: true,
  },
  {
    userId: 1,
    id: 9,
    title: "Research new software tools for project management",
    completed: false,
  },
  {
    userId: 1,
    id: 10,
    title: "Conduct performance reviews for team members",
    completed: true,
  },
  {
    userId: 1,
    id: 11,
    title: "Finalize contract with new vendor",
    completed: true,
  },
  {
    userId: 1,
    id: 12,
    title: "Prepare financial forecast for next year",
    completed: true,
  },
  {
    userId: 1,
    id: 13,
    title: "Clean up project management tools and software",
    completed: false,
  },
  {
    userId: 1,
    id: 14,
    title: "Organize team training session on new tools",
    completed: true,
  },
  {
    userId: 1,
    id: 15,
    title: "Submit tax documentation to accountant",
    completed: true,
  },
  {
    userId: 1,
    id: 16,
    title: "Create a social media content calendar",
    completed: true,
  },
  {
    userId: 1,
    id: 17,
    title: "Analyze customer feedback for product improvements",
    completed: true,
  },
  {
    userId: 1,
    id: 18,
    title: "Research competitors' pricing strategies",
    completed: false,
  },
  {
    userId: 1,
    id: 19,
    title: "Plan team holiday schedule",
    completed: true,
  },
  {
    userId: 1,
    id: 20,
    title: "Develop a marketing strategy for new product launch",
    completed: true,
  },
  {
    userId: 2,
    id: 21,
    title: "Prepare business proposal for potential partner",
    completed: false,
  },
  {
    userId: 2,
    id: 22,
    title: "Update product catalog for next season",
    completed: false,
  },
  {
    userId: 2,
    id: 23,
    title: "Hold interview for new team members",
    completed: true,
  },
  {
    userId: 2,
    id: 24,
    title: "Create customer loyalty program",
    completed: false,
  },
  {
    userId: 2,
    id: 25,
    title: "Test website for bugs and performance issues",
    completed: true,
  },
  {
    userId: 2,
    id: 26,
    title: "Arrange a feedback session with customers",
    completed: false,
  },
  {
    userId: 2,
    id: 27,
    title: "Write content for new blog post",
    completed: true,
  },
  {
    userId: 2,
    id: 28,
    title: "Schedule training session for sales team",
    completed: true,
  },
  {
    userId: 2,
    id: 29,
    title: "Audit company expenses for last quarter",
    completed: false,
  },
  {
    userId: 2,
    id: 30,
    title: "Plan team retreat for next month",
    completed: true,
  },
  {
    userId: 3,
    id: 31,
    title: "Follow up with suppliers for overdue orders",
    completed: false,
  },
  {
    userId: 3,
    id: 32,
    title: "Set up CRM for customer relationship management",
    completed: true,
  },
  {
    userId: 3,
    id: 33,
    title: "Coordinate with design team for marketing materials",
    completed: false,
  },
  {
    userId: 3,
    id: 34,
    title: "Check and reorder inventory for upcoming sales",
    completed: false,
  },
  {
    userId: 3,
    id: 35,
    title: "Design new website layout",
    completed: true,
  },
  {
    userId: 3,
    id: 36,
    title: "Conduct customer survey to gather insights",
    completed: false,
  },
  {
    userId: 3,
    id: 37,
    title: "Optimize email marketing campaigns",
    completed: true,
  },
  {
    userId: 3,
    id: 38,
    title: "Develop an SEO strategy for the company blog",
    completed: true,
  },
  {
    userId: 3,
    id: 39,
    title: "Update privacy policy on company website",
    completed: false,
  },
  {
    userId: 3,
    id: 40,
    title: "Work on company sustainability report",
    completed: true,
  },
  {
    userId: 4,
    id: 41,
    title: "Review employee benefit plans",
    completed: true,
  },
  {
    userId: 4,
    id: 42,
    title: "Finalize partnership agreement",
    completed: false,
  },
  {
    userId: 4,
    id: 43,
    title: "Host a virtual meeting for remote employees",
    completed: true,
  },
  {
    userId: 4,
    id: 44,
    title: "Review and improve customer support process",
    completed: true,
  },
  {
    userId: 4,
    id: 45,
    title: "Revisit the company’s pricing strategy",
    completed: false,
  },
  {
    userId: 4,
    id: 46,
    title: "Attend industry conference for networking",
    completed: false,
  },
  {
    userId: 4,
    id: 47,
    title: "Prepare marketing budget for next quarter",
    completed: true,
  },
  {
    userId: 4,
    id: 48,
    title: "Complete year-end financial review",
    completed: true,
  },
  {
    userId: 4,
    id: 49,
    title: "Organize customer feedback focus group",
    completed: false,
  },
  {
    userId: 4,
    id: 50,
    title: "Start planning the next product launch",
    completed: true,
  }
];
