exports.USERS = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: { lat: "-37.3159", lng: "81.1496" },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: { lat: "-43.9509", lng: "-34.4618" },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
  {
    id: 3,
    name: "Carmen Beck",
    username: "CarmenB",
    email: "carmen.beck@example.com",
    address: {
      street: "321 Elm St",
      suite: "Apt. 8C",
      city: "Dallas",
      zipcode: "75201",
      geo: { lat: "32.7767", lng: "-96.7970" },
    },
    phone: "555-987-6543",
    website: "carmenbeck.com",
    company: {
      name: "Beck Enterprises",
      catchPhrase: "Innovative solutions for the modern world",
      bs: "business solutions",
    },
  },
  {
    id: 4,
    name: "Patricia Johnson",
    username: "PatriciaJ",
    email: "patricia.johnson@example.com",
    address: {
      street: "15 Oak Rd",
      suite: "Suite 20",
      city: "Los Angeles",
      zipcode: "90001",
      geo: { lat: "34.0522", lng: "-118.2437" },
    },
    phone: "555-876-1234",
    website: "patriciajohnson.com",
    company: {
      name: "Johnson Consulting",
      catchPhrase: "Leading with strategy and innovation",
      bs: "management consulting",
    },
  },
  {
    id: 5,
    name: "John Carter",
    username: "JohnC",
    email: "john.carter@example.com",
    address: {
      street: "78 Pine Dr",
      suite: "Apt. 6B",
      city: "Houston",
      zipcode: "77002",
      geo: { lat: "29.7604", lng: "-95.3698" },
    },
    phone: "555-234-5678",
    website: "johncarter.com",
    company: {
      name: "Carter Enterprises",
      catchPhrase: "Transforming business landscapes",
      bs: "corporate strategy",
    },
  },
  {
    id: 6,
    name: "James Brooks",
    username: "JamesB",
    email: "james.brooks@example.com",
    address: {
      street: "20 Westgate Dr",
      suite: "Suite 8",
      city: "San Francisco",
      zipcode: "94105",
      geo: { lat: "37.7749", lng: "-122.4194" },
    },
    phone: "555-777-1234",
    website: "jamesbrooks.com",
    company: {
      name: "Brooks Enterprises",
      catchPhrase: "Global solutions for modern business",
      bs: "corporate strategy",
    },
  },
  {
    id: 7,
    name: "Olivia Martinez",
    username: "OliviaM",
    email: "olivia.martinez@example.com",
    address: {
      street: "60 Liberty Ave",
      suite: "Apt. 2C",
      city: "New York",
      zipcode: "10001",
      geo: { lat: "40.7128", lng: "-74.0060" },
    },
    phone: "555-890-2345",
    website: "oliviamartinez.com",
    company: {
      name: "Martinez & Co.",
      catchPhrase: "Empowering businesses to succeed",
      bs: "financial services",
    },
  },
  {
    id: 8,
    name: "Ethan Lewis",
    username: "EthanL",
    email: "ethan.lewis@example.com",
    address: {
      street: "22 River Walk",
      suite: "Apt. 3D",
      city: "Portland",
      zipcode: "97201",
      geo: { lat: "45.5051", lng: "-122.6750" },
    },
    phone: "555-567-4321",
    website: "ethanlewis.com",
    company: {
      name: "Lewis Innovations",
      catchPhrase: "Innovating with a purpose",
      bs: "engineering services",
    },
  },
  {
    id: 9,
    name: "Amelia Clark",
    username: "AmeliaC",
    email: "amelia.clark@example.com",
    address: {
      street: "5 Ocean View St",
      suite: "Suite 11",
      city: "Miami",
      zipcode: "33101",
      geo: { lat: "25.7617", lng: "-80.1918" },
    },
    phone: "555-657-9876",
    website: "ameliaclark.com",
    company: {
      name: "Clark Solutions",
      catchPhrase: "Helping you achieve excellence",
      bs: "consulting services",
    },
  },
  {
    id: 10,
    name: "William Anderson",
    username: "WilliamA",
    email: "william.anderson@example.com",
    address: {
      street: "123 King St",
      suite: "Suite 4A",
      city: "Houston",
      zipcode: "77002",
      geo: { lat: "29.7604", lng: "-95.3698" },
    },
    phone: "555-321-4321",
    website: "williamanderson.com",
    company: {
      name: "Anderson & Sons",
      catchPhrase: "Crafting your success",
      bs: "business consulting",
    },
  },
  {
    id: 11,
    name: "Sophie Turner",
    username: "SophieT",
    email: "sophie.turner@example.com",
    address: {
      street: "10 Springwood Dr",
      suite: "Apt. 2E",
      city: "Austin",
      zipcode: "78701",
      geo: { lat: "30.2672", lng: "-97.7431" },
    },
    phone: "555-432-9876",
    website: "sophieturner.com",
    company: {
      name: "Turner Technologies",
      catchPhrase: "Leading innovation in tech",
      bs: "software development",
    },
  },
  {
    id: 12,
    name: "Gabriel Davis",
    username: "GabrielD",
    email: "gabriel.davis@example.com",
    address: {
      street: "45 Oakwood Rd",
      suite: "Suite 6",
      city: "Charlotte",
      zipcode: "28202",
      geo: { lat: "35.2271", lng: "-80.8431" },
    },
    phone: "555-123-6543",
    website: "gabrieldavis.com",
    company: {
      name: "Davis Enterprises",
      catchPhrase: "Shaping the future of business",
      bs: "consulting and strategy",
    },
  },
  {
    id: 13,
    name: "Isaac Wilson",
    username: "IsaacW",
    email: "isaac.wilson@example.com",
    address: {
      street: "123 Sunset Rd",
      suite: "Apt. 10B",
      city: "Boston",
      zipcode: "02108",
      geo: { lat: "42.3601", lng: "-71.0589" },
    },
    phone: "555-345-6789",
    website: "isaacwilson.com",
    company: {
      name: "Wilson Strategies",
      catchPhrase: "Creating paths for progress",
      bs: "marketing solutions",
    },
  },
  {
    id: 14,
    name: "Charlotte Harris",
    username: "CharlotteH",
    email: "charlotte.harris@example.com",
    address: {
      street: "89 Elmwood Ave",
      suite: "Suite 12",
      city: "Chicago",
      zipcode: "60602",
      geo: { lat: "41.8781", lng: "-87.6298" },
    },
    phone: "555-432-1234",
    website: "charlotteharris.com",
    company: {
      name: "Harris Innovations",
      catchPhrase: "Innovative solutions for tomorrow",
      bs: "technology services",
    },
  },
  {
    id: 15,
    name: "Eliot Stewart",
    username: "EliotS",
    email: "eliot.stewart@example.com",
    address: {
      street: "102 Maple St",
      suite: "Suite 8D",
      city: "Denver",
      zipcode: "80202",
      geo: { lat: "39.7392", lng: "-104.9903" },
    },
    phone: "555-123-7654",
    website: "eliotstewart.com",
    company: {
      name: "Stewart Consulting",
      catchPhrase: "Reaching new heights together",
      bs: "business and strategy",
    },
  },
  {
    id: 16,
    name: "Scarlett Moore",
    username: "ScarlettM",
    email: "scarlett.moore@example.com",
    address: {
      street: "58 Crescent Ave",
      suite: "Apt. 7C",
      city: "Dallas",
      zipcode: "75205",
      geo: { lat: "32.7767", lng: "-96.7970" },
    },
    phone: "555-567-8901",
    website: "scarlettmoore.com",
    company: {
      name: "Moore Solutions",
      catchPhrase: "Delivering effective solutions",
      bs: "consulting services",
    },
  },
  {
    id: 17,
    name: "Daniel Smith",
    username: "DanielS",
    email: "daniel.smith@example.com",
    address: {
      street: "22 Broadway St",
      suite: "Suite 3",
      city: "San Francisco",
      zipcode: "94107",
      geo: { lat: "37.7749", lng: "-122.4194" },
    },
    phone: "555-234-5678",
    website: "danielsmith.com",
    company: {
      name: "Smith Enterprises",
      catchPhrase: "Creative solutions for a complex world",
      bs: "consulting and design",
    },
  },
  {
    id: 18,
    name: "Maya Robinson",
    username: "MayaR",
    email: "maya.robinson@example.com",
    address: {
      street: "16 Birchwood Dr",
      suite: "Apt. 3F",
      city: "Philadelphia",
      zipcode: "19103",
      geo: { lat: "39.9526", lng: "-75.1652" },
    },
    phone: "555-654-3210",
    website: "mayarobinson.com",
    company: {
      name: "Robinson & Co.",
      catchPhrase: "Transforming business practices",
      bs: "management consulting",
    },
  },
  {
    id: 19,
    name: "Liam White",
    username: "LiamW",
    email: "liam.white@example.com",
    address: {
      street: "89 Wall St",
      suite: "Apt. 9E",
      city: "New York",
      zipcode: "10005",
      geo: { lat: "40.7128", lng: "-74.0060" },
    },
    phone: "555-234-5678",
    website: "liamwhite.com",
    company: {
      name: "White & Associates",
      catchPhrase: "Strategic growth through innovation",
      bs: "financial services",
    },
  },
  {
    id: 20,
    name: "Benjamin King",
    username: "BenjaminK",
    email: "benjamin.king@example.com",
    address: {
      street: "13 Spruce Rd",
      suite: "Suite 2C",
      city: "Los Angeles",
      zipcode: "90003",
      geo: { lat: "34.0522", lng: "-118.2437" },
    },
    phone: "555-678-1234",
    website: "benjaminking.com",
    company: {
      name: "King Solutions",
      catchPhrase: "Revolutionizing business operations",
      bs: "business consulting",
    },
  },
  // Users from id 2 to 20
  {
    id: 21,
    name: "Maria Garcia",
    username: "MariaG",
    email: "maria.garcia@example.com",
    address: {
      street: "123 Pine St",
      suite: "Apt. 4A",
      city: "Madrid",
      zipcode: "28001",
      geo: { lat: "40.4168", lng: "-3.7038" },
    },
    phone: "555-432-1111",
    website: "mariagarcia.com",
    company: {
      name: "Garcia Tech",
      catchPhrase: "Innovating solutions for tomorrow",
      bs: "software development",
    },
  },
  {
    id: 22,
    name: "David Peterson",
    username: "DavidP",
    email: "david.peterson@example.com",
    address: {
      street: "10 Sunset Blvd",
      suite: "Suite 9",
      city: "Los Angeles",
      zipcode: "90028",
      geo: { lat: "34.0522", lng: "-118.2437" },
    },
    phone: "555-213-9087",
    website: "davidpeterson.com",
    company: {
      name: "Peterson Innovations",
      catchPhrase: "Redefining the future of tech",
      bs: "AI research",
    },
  },
  {
    id: 23,
    name: "Jessica Stevens",
    username: "JessicaS",
    email: "jessica.stevens@example.com",
    address: {
      street: "50 Greenway Dr",
      suite: "Suite 5",
      city: "Chicago",
      zipcode: "60614",
      geo: { lat: "41.8781", lng: "-87.6298" },
    },
    phone: "555-321-6543",
    website: "jessicastevens.com",
    company: {
      name: "Stevens Consulting",
      catchPhrase: "Bringing clarity to your business",
      bs: "business consulting",
    },
  },
  {
    id: 24,
    name: "James Brooks",
    username: "JamesB",
    email: "james.brooks@example.com",
    address: {
      street: "20 Westgate Dr",
      suite: "Suite 8",
      city: "San Francisco",
      zipcode: "94105",
      geo: { lat: "37.7749", lng: "-122.4194" },
    },
    phone: "555-777-1234",
    website: "jamesbrooks.com",
    company: {
      name: "Brooks Enterprises",
      catchPhrase: "Global solutions for modern business",
      bs: "corporate strategy",
    },
  },
  {
    id: 25,
    name: "Olivia Martinez",
    username: "OliviaM",
    email: "olivia.martinez@example.com",
    address: {
      street: "60 Liberty Ave",
      suite: "Apt. 2C",
      city: "New York",
      zipcode: "10001",
      geo: { lat: "40.7128", lng: "-74.0060" },
    },
    phone: "555-890-2345",
    website: "oliviamartinez.com",
    company: {
      name: "Martinez & Co.",
      catchPhrase: "Empowering businesses to succeed",
      bs: "financial services",
    },
  },
  {
    id: 26,
    name: "Ethan Lewis",
    username: "EthanL",
    email: "ethan.lewis@example.com",
    address: {
      street: "22 River Walk",
      suite: "Apt. 3D",
      city: "Portland",
      zipcode: "97201",
      geo: { lat: "45.5051", lng: "-122.6750" },
    },
    phone: "555-567-4321",
    website: "ethanlewis.com",
    company: {
      name: "Lewis Innovations",
      catchPhrase: "Innovating with a purpose",
      bs: "engineering services",
    },
  },
  {
    id: 27,
    name: "Amelia Clark",
    username: "AmeliaC",
    email: "amelia.clark@example.com",
    address: {
      street: "5 Ocean View St",
      suite: "Suite 11",
      city: "Miami",
      zipcode: "33101",
      geo: { lat: "25.7617", lng: "-80.1918" },
    },
    phone: "555-657-9876",
    website: "ameliaclark.com",
    company: {
      name: "Clark Solutions",
      catchPhrase: "Helping you achieve excellence",
      bs: "consulting services",
    },
  },
  {
    id: 28,
    name: "William Anderson",
    username: "WilliamA",
    email: "william.anderson@example.com",
    address: {
      street: "123 King St",
      suite: "Suite 4A",
      city: "Houston",
      zipcode: "77002",
      geo: { lat: "29.7604", lng: "-95.3698" },
    },
    phone: "555-321-4321",
    website: "williamanderson.com",
    company: {
      name: "Anderson & Sons",
      catchPhrase: "Crafting your success",
      bs: "business consulting",
    },
  },
  {
    id: 29,
    name: "Sophie Turner",
    username: "SophieT",
    email: "sophie.turner@example.com",
    address: {
      street: "10 Springwood Dr",
      suite: "Apt. 2E",
      city: "Austin",
      zipcode: "78701",
      geo: { lat: "30.2672", lng: "-97.7431" },
    },
    phone: "555-432-9876",
    website: "sophieturner.com",
    company: {
      name: "Turner Technologies",
      catchPhrase: "Leading innovation in tech",
      bs: "software development",
    },
  },
  {
    id: 30,
    name: "Gabriel Davis",
    username: "GabrielD",
    email: "gabriel.davis@example.com",
    address: {
      street: "45 Oakwood Rd",
      suite: "Suite 6",
      city: "Charlotte",
      zipcode: "28202",
      geo: { lat: "35.2271", lng: "-80.8431" },
    },
    phone: "555-123-6543",
    website: "gabrieldavis.com",
    company: {
      name: "Davis Enterprises",
      catchPhrase: "Shaping the future of business",
      bs: "consulting and strategy",
    },
  },
  {
    id: 31,
    name: "Isaac Wilson",
    username: "IsaacW",
    email: "isaac.wilson@example.com",
    address: {
      street: "123 Sunset Rd",
      suite: "Apt. 10B",
      city: "Boston",
      zipcode: "02108",
      geo: { lat: "42.3601", lng: "-71.0589" },
    },
    phone: "555-345-6789",
    website: "isaacwilson.com",
    company: {
      name: "Wilson Strategies",
      catchPhrase: "Creating paths for progress",
      bs: "marketing solutions",
    },
  },
  {
    id: 32,
    name: "Charlotte Harris",
    username: "CharlotteH",
    email: "charlotte.harris@example.com",
    address: {
      street: "89 Elmwood Ave",
      suite: "Suite 12",
      city: "Chicago",
      zipcode: "60602",
      geo: { lat: "41.8781", lng: "-87.6298" },
    },
    phone: "555-456-7890",
    website: "charlotteharris.com",
    company: {
      name: "Harris Consulting",
      catchPhrase: "Empowering your business to grow",
      bs: "strategic consulting",
    },
  },
  {
    id: 33,
    name: "Jack Roberts",
    username: "JackR",
    email: "jack.roberts@example.com",
    address: {
      street: "12 Maple St",
      suite: "Suite 2",
      city: "Phoenix",
      zipcode: "85001",
      geo: { lat: "33.4484", lng: "-112.0740" },
    },
    phone: "555-678-1234",
    website: "jackroberts.com",
    company: {
      name: "Roberts Enterprises",
      catchPhrase: "Success through innovation",
      bs: "business solutions",
    },
  },
  {
    id: 34,
    name: "Lucas Martinez",
    username: "LucasM",
    email: "lucas.martinez@example.com",
    address: {
      street: "22 Ocean Dr",
      suite: "Apt. 5D",
      city: "San Diego",
      zipcode: "92101",
      geo: { lat: "32.7157", lng: "-117.1611" },
    },
    phone: "555-890-1234",
    website: "lucasmartinez.com",
    company: {
      name: "Martinez Consulting",
      catchPhrase: "Delivering excellence across industries",
      bs: "consulting services",
    },
  },
  {
    id: 35,
    name: "Hannah Thomas",
    username: "HannahT",
    email: "hannah.thomas@example.com",
    address: {
      street: "3 High Street",
      suite: "Suite 15",
      city: "Seattle",
      zipcode: "98101",
      geo: { lat: "47.6062", lng: "-122.3321" },
    },
    phone: "555-234-6789",
    website: "hannahthomas.com",
    company: {
      name: "Thomas Innovations",
      catchPhrase: "Technology for a better future",
      bs: "tech solutions",
    },
  }
]
