exports.USERS = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
      geo: { lat: "-37.3159", lng: "81.1496" },
    },
    phone: "1-770-736-8031 x56442",
    website: "hildegard.org",
    company: {
      name: "Romaguera-Crona",
      catchPhrase: "Multi-layered client-server neural-net",
      bs: "harness real-time e-markets",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
      geo: { lat: "-43.9509", lng: "-34.4618" },
    },
    phone: "010-692-6593 x09125",
    website: "anastasia.net",
    company: {
      name: "Deckow-Crist",
      catchPhrase: "Proactive didactic contingency",
      bs: "synergize scalable supply-chains",
    },
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
      geo: { lat: "-68.6102", lng: "-47.0653" },
    },
    phone: "1-463-123-4447",
    website: "ramiro.info",
    company: {
      name: "Romaguera-Jacobson",
      catchPhrase: "Face to face bifurcated interface",
      bs: "e-enable strategic applications",
    },
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
      geo: { lat: "29.4572", lng: "-164.2990" },
    },
    phone: "493-170-9623 x156",
    website: "kale.biz",
    company: {
      name: "Robel-Corkery",
      catchPhrase: "Multi-tiered zero tolerance productivity",
      bs: "transition cutting-edge web services",
    },
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
      geo: { lat: "-31.8129", lng: "62.5342" },
    },
    phone: "(254)954-1289",
    website: "demarco.info",
    company: {
      name: "Keebler LLC",
      catchPhrase: "User-centric fault-tolerant solution",
      bs: "revolutionize end-to-end systems",
    },
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
      geo: { lat: "-71.4197", lng: "71.7478" },
    },
    phone: "1-477-935-8478 x6430",
    website: "ola.org",
    company: {
      name: "Considine-Lockman",
      catchPhrase: "Synchronised bottom-line interface",
      bs: "e-enable innovative applications",
    },
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
      geo: { lat: "24.8918", lng: "21.8984" },
    },
    phone: "210.067.6132",
    website: "elvis.io",
    company: {
      name: "Johns Group",
      catchPhrase: "Configurable multimedia task-force",
      bs: "generate enterprise e-tailers",
    },
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
      geo: { lat: "-14.3990", lng: "-120.7677" },
    },
    phone: "586.493.6943 x140",
    website: "jacynthe.com",
    company: {
      name: "Abernathy Group",
      catchPhrase: "Implemented secondary concept",
      bs: "e-enable extensible e-tailers",
    },
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
      geo: { lat: "24.6463", lng: "-168.8889" },
    },
    phone: "(775)976-6794 x41206",
    website: "conrad.com",
    company: {
      name: "Yost and Sons",
      catchPhrase: "Switchable contextually-based project",
      bs: "aggregate real-time technologies",
    },
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
      geo: { lat: "-38.2386", lng: "57.2232" },
    },
    phone: "024-648-3804",
    website: "ambrose.net",
    company: {
      name: "Hoeger LLC",
      catchPhrase: "Centralized empowering task-force",
      bs: "target end-to-end models",
    },
  },
  {
    id: 11,
    name: "John Doe",
    username: "JohnD",
    email: "johndoe@example.com",
    address: {
      street: "123 Main St",
      suite: "Apt. 1",
      city: "Springfield",
      zipcode: "12345",
      geo: { lat: "40.7128", lng: "-74.0060" },
    },
    phone: "555-123-4567",
    website: "johndoe.com",
    company: {
      name: "Doe Enterprises",
      catchPhrase: "Innovating the future",
      bs: "leading-edge solutions",
    },
  },
  {
    id: 12,
    name: "Alice Johnson",
    username: "AliceJ",
    email: "alice.johnson@example.com",
    address: {
      street: "456 Oak St",
      suite: "Suite 5",
      city: "Metropolis",
      zipcode: "67890",
      geo: { lat: "34.0522", lng: "-118.2437" },
    },
    phone: "555-987-6543",
    website: "alicejohnson.com",
    company: {
      name: "Johnson Co.",
      catchPhrase: "Transforming ideas into reality",
      bs: "creative services",
    },
  },
  {
    id: 13,
    name: "Bob Smith",
    username: "BobS",
    email: "bob.smith@example.com",
    address: {
      street: "789 Pine St",
      suite: "Apt. 3B",
      city: "Gotham",
      zipcode: "54321",
      geo: { lat: "41.8781", lng: "-87.6298" },
    },
    phone: "555-555-5555",
    website: "bobsmith.com",
    company: {
      name: "Smith Solutions",
      catchPhrase: "Your problem-solving partner",
      bs: "consulting services",
    },
  },
  {
    id: 14,
    name: "Eva Lee",
    username: "EvaL",
    email: "eva.lee@example.com",
    address: {
      street: "101 Maple Ave",
      suite: "Suite 2",
      city: "Smalltown",
      zipcode: "11223",
      geo: { lat: "36.7783", lng: "-119.4179" },
    },
    phone: "555-234-6789",
    website: "evalee.com",
    company: {
      name: "Lee Corp.",
      catchPhrase: "The power of innovation",
      bs: "advanced technology",
    },
  },
  {
    id: 15,
    name: "David King",
    username: "DavidK",
    email: "david.king@example.com",
    address: {
      street: "202 Birch Rd",
      suite: "Apt. 4C",
      city: "Bay Area",
      zipcode: "23456",
      geo: { lat: "37.7749", lng: "-122.4194" },
    },
    phone: "555-777-8888",
    website: "davidking.com",
    company: {
      name: "King Enterprises",
      catchPhrase: "Where vision meets execution",
      bs: "business solutions",
    },
  },
  {
    id: 16,
    name: "Sophia Martinez",
    username: "SophiaM",
    email: "sophia.martinez@example.com",
    address: {
      street: "303 Cherry Lane",
      suite: "Suite 6",
      city: "Riverside",
      zipcode: "65432",
      geo: { lat: "33.8688", lng: "-118.2283" },
    },
    phone: "555-321-4321",
    website: "sophiamartinez.com",
    company: {
      name: "Martinez Solutions",
      catchPhrase: "Solving problems with passion",
      bs: "professional consulting",
    },
  },
  {
    id: 17,
    name: "Daniel Hernandez",
    username: "DanielH",
    email: "daniel.hernandez@example.com",
    address: {
      street: "404 Pine Ridge",
      suite: "Apt. 7D",
      city: "Sunnydale",
      zipcode: "76543",
      geo: { lat: "36.1627", lng: "-86.7816" },
    },
    phone: "555-444-5555",
    website: "danielhernandez.com",
    company: {
      name: "Hernandez & Partners",
      catchPhrase: "Bringing clarity to complexity",
      bs: "legal consulting",
    },
  },
  {
    id: 18,
    name: "Oliver Taylor",
    username: "OliverT",
    email: "oliver.taylor@example.com",
    address: {
      street: "505 Cedar Blvd",
      suite: "Suite 8",
      city: "Lakeside",
      zipcode: "87654",
      geo: { lat: "40.7306", lng: "-73.9352" },
    },
    phone: "555-555-1234",
    website: "olivertaylor.com",
    company: {
      name: "Taylor Industries",
      catchPhrase: "Efficiency at its best",
      bs: "manufacturing",
    },
  },
  {
    id: 19,
    name: "Emily Johnson",
    username: "EmilyJ",
    email: "emily.johnson@example.com",
    address: {
      street: "123 Elm St",
      suite: "Apt. 9",
      city: "Lakewood",
      zipcode: "91234",
      geo: { lat: "39.7392", lng: "-104.9903" },
    },
    phone: "555-333-7777",
    website: "emilyjohnson.com",
    company: {
      name: "Johnson Digital",
      catchPhrase: "Innovation is our strength",
      bs: "digital marketing",
    },
  },
  {
    id: 20,
    name: "Lucas White",
    username: "LucasW",
    email: "lucas.white@example.com",
    address: {
      street: "678 River Rd",
      suite: "Suite 12",
      city: "Riverside",
      zipcode: "87654",
      geo: { lat: "35.2271", lng: "-80.8431" },
    },
    phone: "555-444-6666",
    website: "lucaswhite.com",
    company: {
      name: "White Enterprises",
      catchPhrase: "Reaching new heights",
      bs: "global consultancy",
    },
  },
  // Add users from id 21 to 50 in the same pattern...
];
